// src/ui/App.vue
<script setup lang="ts">
import SourceSelectorVue from './components/SourceSelector.vue';
import VideoPlayerVue from './components/VideoPlayer.vue';
import SubTrackVue from './components/SubTrack.vue';
import { DirectoryTree } from 'directory-tree';
import { Ref, ref } from 'vue';
import { FileFilter } from 'electron';

const selectedVideo: Ref<DirectoryTree | undefined> = ref(undefined);
const selectedSubs: Ref<DirectoryTree | undefined> = ref(undefined);

const videoFilters: FileFilter[] = [{ name: 'Select Video', extensions: ['mp4', 'mkv'] }];
const subsFilters: FileFilter[] = [{ name: 'Select Subs', extensions: ['srt', 'ass', 'webvtt'] }];
</script>

<template>
  <div class="bg-zinc-500 flex flex-col w-1/4 ">
    <SourceSelectorVue :id="'video'" :filters="videoFilters" @selection-changed="(sel, _) => selectedVideo = sel"
      class="h-1/2" :title="'Videos'" />
    <SourceSelectorVue :id="'subs'" :filters="subsFilters" @selection-changed="(sel, _) => selectedSubs = sel"
      class="h-1/2" :title="'Subtitles'" />
  </div>
  <div class="flex flex-col flex-1 h-full">
    <VideoPlayerVue :subs-path="selectedSubs" :video-path="selectedVideo" />
    <SubTrackVue />
    <div class="w-full h-6 flex bg-zinc-500 text-gray-100 font-bold text-sm ">
      <div class="flex-1 flex h-full items-center">
        <img src="assets/video-svgrepo-com.svg" class="mr-0.5 w-5" alt="Video file icon">
        <h1>{{ selectedVideo?.name }}</h1>
      </div>
      <div class=" w-[1px] mx-1 h-full bg-opacity-20 bg-black"></div>
      <div class="flex-1 flex h-full items-center">
        <img src="assets/subtitles-svgrepo-com.svg" class="mr-1 w-5" alt="Subtitles file icon">
        <h1>{{ selectedSubs?.name }}</h1>
      </div>
    </div>
  </div>
</template>

<style>
#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

html,
body,
#app {
  height: 100%;
  width: 100%;
}

#app {
  display: flex;
}
</style>

// src/renderer/src/App.svelte
<script lang="ts">
  import type { DirectoryTree } from "directory-tree";
  import type { FileFilter } from "electron";
  import Icon from "@iconify/svelte";
  import { getVttSubsUrl } from "./lib/utils";
  import prettyMilliseconds from "pretty-ms";
  import VideoPlayer from "./lib/VideoPlayer.svelte";
  import SourceSelector from "./lib/SourceSelector.svelte";
  import AudioTrack from "./lib/AudioTrack.svelte";
  import SubTrack from "./lib/SubTrack.svelte";

  const videoFilters: FileFilter[] = [
    { name: "Select Video", extensions: ["mp4", "mkv"] },
  ];
  const subsFilters: FileFilter[] = [
    { name: "Select Subs", extensions: ["srt", "ass", "vtt"] },
  ];

  let selectedVideo: DirectoryTree | undefined = undefined;
  let selectedSubs: DirectoryTree | undefined = undefined;
  let videoPoint = 0;
  let subsOffset = 0;
  let paused = true;

  let subsUrl = "";
  $: {
    if (selectedSubs !== undefined) {
      getVttSubsUrl(selectedSubs).then((url) => (subsUrl = url));
    } else {
      subsUrl = "";
    }
  }

  let prettyOffset: string = "";
  $: prettyOffset =
    (subsOffset >= 0 ? "+" : "-") +
    prettyMilliseconds(Math.abs(subsOffset) * 1000, {
      secondsDecimalDigits: 2,
    });
</script>

<div class="h-full w-full flex">
  <div class="bg-neutral-600 flex flex-col w-1/5 min-w-[200px]">
    <SourceSelector
      id="video"
      filters={videoFilters}
      bind:selection={selectedVideo}
      class="h-1/2"
      title="Videos"
    />
    <SourceSelector
      id="subs"
      filters={subsFilters}
      bind:selection={selectedSubs}
      class="h-1/2"
      title="Subtitles"
    />
  </div>
  <div class="flex flex-col h-full border-neutral-800 border-l-[1px] flex-1">
    <VideoPlayer
      class="h-2/3 bg-black"
      bind:currentTime={videoPoint}
      offset={subsOffset}
      videoPath={selectedVideo}
      {subsUrl}
      {paused}
    />
    <SubTrack
      class="border-y-[1px] border-neutral-800"
      {subsUrl}
      pxpersecond={100}
      point={videoPoint}
      bind:offset={subsOffset}
    />
    <AudioTrack {selectedVideo} point={videoPoint} pxpersecond={100} />
    <div
      class="w-full h-6 flex bg-neutral-700 text-gray-100 text-sm border-neutral-800 border-t-[1px]"
    >
      <div class="flex-1 flex h-full items-center">
        <Icon class="mr-1 ml-1" icon="bx:video" />
        <h1>{selectedVideo ? selectedVideo.name : ""}</h1>
      </div>
      <div class=" w-[1px] mx-1 h-full bg-neutral-800" />
      <div class="flex-1 flex h-full items-center">
        <Icon class="mr-1" icon="fluent:subtitles-16-regular" />
        <h1>{selectedSubs ? selectedSubs.name : ""}</h1>
        <div class="flex-1" />
        <h1 class="mr-1">{prettyOffset}</h1>
      </div>
    </div>
  </div>
</div>

<style>
</style>
